

DROP TABLE IF EXISTS t_tcc;
CREATE TABLE t_tcc (
  id          UUID NOT NULL,
  times       tinyint(2) NOT NULL,
  status      tinyint(2) NOT NULL,
  expire      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  create      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ; -- ENGINE=InnoDB DEFAULT CHARSET=latin1;


DROP TABLE IF EXISTS t_tcc_link;
CREATE TABLE t_tcc_link (
  id          UUID NOT NULL,
  tcc_id      UUID NOT NULL,
  uri         varchar(200) NOT NULL,
  entity_id   UUID NOT NULL,
  status      tinyint(2) NOT NULL,
  expire      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  create      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ; -- ENGINE=InnoDB DEFAULT CHARSET=latin1;
