
spring:
  application:
    name: springboot-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/forsrc/MyPig-config



server:
  port: 12000
  context-path: /config

